name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: azure/docker-login@v1
        with:
          login-server: ataacr.azurecr.io
          username: ${{ secrets.ATA_ACR_USERNAME }}
          password: ${{ secrets.ATA_ACR_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ataacr.azurecr.io/blockscout-frontend:${{ github.sha }}
